server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: Sourav#8699
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    
  application:
    name: HOTEL-SERVICE-MS

  config:
    import: configserver:http://localhost:8088

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-95161145.okta.com/oauth2/default
      client:
        registration:
          hotel-service-client:
            provider: okta
            authorizationGrantType: client_credentials
            scope:
              - internal
            client-id: 0oadblbh95To3qKXP5d7
            client-secret: 63c0kPtI6TRWTNFM_rHfoIltKIC3oGeaM_2aqd7eWZQBJE6_E6okXxCaF3KV9Alu
        provider:
          okta:
            issuerUri: https://dev-95161145.okta.com/oauth2/default

okta:
  oauth2:
    issuer: https://dev-95161145.okta.com/oauth2/default
    audience: api://default

management:
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelServiceBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  ratelimiter:
    instances:
      hotelServiceLimiter:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 2s

