server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices
      
  application:
    name: RATING-SERVICE-MS

  config:
    import: configserver:http://localhost:8088

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-95161145.okta.com/oauth2/default

okta:
  oauth2:
    issuer: https://dev-95161145.okta.com/oauth2/default
    audience: api://default