server:
  port: 8086

spring:
  application:
    name: API-GATEWAY

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-95161145.okta.com/oauth2/default

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE-MS
          uri: lb://USER-SERVICE-MS
          predicates:
            - Path=/api/v1/user/**
        #          filters:
        #            - name: CircuitBreaker
        #              args:
        #                - name: userCircuitBreaker
        #                - fallbackUri: forward:/api/error/fallback/contactSupport

        - id: HOTEL-SERVICE-MS
          uri: lb://HOTEL-SERVICE-MS
          predicates:
            - Path=/api/v1/hotel/**, /api/v1/staff/**
        #          filters:
        #            - name: CircuitBreaker
        #              args:
        #                - name: hotelCircuitBreaker
        #                - fallbackUri: forward:/api/error/fallback/contactSupport

        - id: RATING-SERVICE-MS
          uri: lb://RATING-SERVICE-MS
          predicates:
            - Path=/api/v1/rating/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                - name: ratingCircuitBreaker
#                - fallbackUri: forward:/api/error/fallback/contactSupport

okta:
  oauth2:
    issuer: https://dev-95161145.okta.com/oauth2/default
    audience: api://default

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # Indicates whether this instance should register its information with eureka server for discovery by others
    fetch-registry: true # Indicates whether this client should fetch eureka registry information from eureka server.
    service-url:
      defaultZone: http://localhost:8761/eureka
    should-unregister-on-shutdown: true

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#        web: DEBUG
#    com:
#      ms:
#        gateway: DEBUG